name: Build Flutter app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installer Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Installer les dépendances
      run: flutter pub get

    - name: Construire l’app Android
      run: flutter build apk --release

